# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

# /home/travis/build/freeonisland/wordpress
# /home/travis/.composer

language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
 # - 5.2
  # aliased to 5.3.29
 # - 5.3
  # aliased to a recent 5.4.x version
 # - 5.4
  # aliased to a recent 5.5.x version
 # - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
#  - 7.0
  # aliased to a recent hhvm version
#  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
# export DB=mysql
env:
  global:
  - secure: u39amh5sTl/vEUvYL9JBkNHFPSqd38Ur8m3GNWtrjgz1erYQt+a2DNhz9poov47dGYtMnaJR7g9sDhocyJP9pphArfzR3I2177Wpbkqi/g9wmmeqz6oB2Iz5pFtNCwmTsoSuo3883LFbVSrGpy05jS14Lmzeynr5inwupbvH4rb8DkOoWVCRLhJXbCNuO3Tu/5FzPdFHKFEiMnC2yfSF00rhOoUvYrodwvUd7s2Hm+ggZ2q9AKw8z8sni62Z+iu8x+49w4i3xomBlLNgYv0VhfwbOx7GxVOIC3QoAMCxEtev+g/gN0hx57Y9jzV4IhsHm0t5gLp02EF6k0FMlenZBu3sYxDYihnCNZ2zmrJsFb1pQ2IBR/ztAeaNckEMxUXoD859/aE7dnJffyMA2MSPG2lUHf4+db3+ySsG3LXzZH6O59OZLSEXh9p6J2kRW+utlUbUcMesnWcEJV/uwd8+nwCtye2nMr1RYq+gHtraO/Pp6+VAXYt8Y/xTw8041LKlH8H5r6HTTB8I0wLGka59UY1GeTVqTTyctD6FNGJ6BlT9pC/SkSFtcD+TNANDFXoC6zRWSxbK0GzUocRvH5nUqnrjAGhXf3pFU2J4QEPiInS+LPkEhgEpvl+QvuJF05g8yCsTjnNnYkTS444osbTU12pZWafMtSr9Wh1TzBfblh4=
  - secure: ArlfSrr9xvUCv3o+hNB2D6C6JK/52QWEBdoJfWga7Fa6464R5U1F7TdI2btUfVIMBYodynJ7gAMX/BAaw5Ms08C/86XGp4WP6fYDtm/D5OtlTLG3L/5j7Y2wVm7oIexjxj69d8JmHN7qTsoGoOHlt/bgZ3RVocHa34mdZowjEQvTmFHYBq124m7jwnn1kKkDAFMl41NxXKFSuy3/Eu3sBAnMn0g++il20l98gfKk/WAhOM/fr1Ba3QSmS+3lveEeJ1V760Wu4zyG+Hj+uoeEV/Q96A5RMBvRQ+apGA9HsgvJ1rgPV1N6keU6D0HgIbIAF2x7y+J0m9NguUR4sGzmguceJo2uawSDt7W+M96F7EHZbAwdyrvzEauuprKoI4DEInvfQF9oK/rLNzl+9EMdC6XkFmpaclDVkwap7cvkbg5ZLuuKQbkJHz8GkK3VQI8e1rbYp9VjzarFk3LFpA2yJfS524B0hfxJNpUwFes4CocID8WoRdEpjMcnDYV6GdzNuxcBGclHDkQywTb+bQWN96zWEzeUCbYZQxPquDfJydFHKE7sob6z8dQt/GYU/mPE3JMj6NVfhTtqkLPI0ypnSF5UN0YL5fr97YXZ/4SCb9q+JJlxZWhFyP9n/KrhQossndC08q2LnbCdP4hLa+3MqP9dK2Aw8uidN/1Bh8BiahY=

  - DB=mysql

  - FOO=foo BAR=bar
  - FOO=bar BAR=foo
#  - DB=pgsql

cache:
  directories:
    - $HOME/.composer/cache
    - /home/travis/.config/composer/cache
    - /home/travis/.composer/cache

before_install:
    # composer global require zendframework/zendframework ^3
    - openssl aes-256-cbc -K $encrypted_e25d799e430b_key -iv $encrypted_e25d799e430b_iv -in id_rsa_64.enc -out id_rsa_64 -d

# optionally set up exclusions and allowed failures in the matrix
matrix:
 # exclude:
 #   - php: hhvm
 #     env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
 # allow_failures:
 #   - php: 7.0
 #   - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:

 #  - composer install --dev 
 # - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
 # - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
 # - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
 
 # git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
 # - git fetch --unshallow
 # - git fetch origin

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
    - composer test
# phpunit --configuration phpunit.xml.dist

after_success:
    - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
    - curl --ftp-create-dirs
       -T license.txt
       --key /tmp/sftp_rsa
       sftp://${SSHLOGIN}:${SSHPASS}@ssh.cluster007.hosting.ovh.net/wordpress_pre
     #sftp://${SSHLOGIN}:${SFTP_PASSWORD}@example.com/directory/filename
    #- scp --ftp-create-dirs 
     #   -T filename
      #  sftp://${SSHLOGIN}:${SSHPASS}@ssh.cluster007.hosting.ovh.net -p 22
# configure notifications (email, IRC, campfire etc)
# notifications:
# irc: "irc.freenode.org#yourfavouriteroomfortravis"

  #email:
   # - travis-ci@kitpages.fr
   